### ISSUE TITLE
The link for latexdiff in the `Research & writing tips` seems to be outdated

### ISSUE THREAD

**Issue by zfengyan** [tudelft3d/geo2020#17]
The link for latexdiff (http://ctan.mirrorcatalogs.com/support/latexdiff/doc/latexdiff-man.pdf) seems to be outdated.

The location of the source code:
https://github.com/tudelft3d/geo2020/blob/217b61568135addb64cd01f14557580c4522de10/tips/index.md?plain=1#L141.

**Comment by hugoledoux** [comment]
cheers, fixed: 2bc44a0c2451871d6583057054de60884de7ef89
